// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI.Slab;

[GenerateTypedNameReferences]
public sealed partial class ClockWorkSlabWindow : FancyWindow
{
    public ClockWorkSlabWindow(ClockworkSlabBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
    }
}
