// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI;

[GenerateTypedNameReferences]
public sealed partial class ClockWorkSlabWindow : FancyWindow
{
    public ClockWorkSlabWindow()
    {
        RobustXamlLoader.Load(this);

        SectionOne.OnPressed += _ => SetupSection(ClockworkSlabSection.Guide);
        SectionTwo.OnPressed += _ => SetupSection(ClockworkSlabSection.Scriptures);
    }

    private void SetupSection(ClockworkSlabSection section)
    {
        Menu.Visible = false;

        switch (section)
        {
            case ClockworkSlabSection.Guide:
            {
                var guideSection = new CogSlabGuideSection();
                ViewContainer.AddChild(guideSection);
                break;
            }
        }
    }
}

public enum ClockworkSlabSection : byte
{
    Guide,
    Scriptures,
}
