// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// A CogSlabSection houses a certain amount of <see cref="CogSlabPage"/>
/// A section supports turning a page (left, right) and going back to the main window of Clockwork Slab
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabSection : Control
{
    /// <summary>
    /// Each section has a list of pages, which are dynamically added
    /// </summary>
    private List<CogSlabPage> _cogSlabPages = new();

    /// <summary>
    /// The current page in view
    /// </summary>
    private int _currentPage;

    /// <summary>
    /// Whether we can turn the page forwards
    /// </summary>
    private bool CanPressNextButton => _currentPage >= _cogSlabPages.Count - 1;

    /// <summary>
    /// Whether we can turn the page backwards
    /// </summary>
    private bool CanPressPrevButton => _currentPage == 0;

    public CogSlabSection()
    {
        RobustXamlLoader.Load(this);

        PrevButton.OnPressed += PrevButtonOnOnPressed;
        NextButton.OnPressed += NextButtonOnOnPressed;
    }

    private void NextButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        TurnPage(1);
    }

    private void PrevButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        TurnPage(-1);
    }

    /// <summary>
    /// Adds a page to <see cref="_cogSlabPages"/>
    /// </summary>
    public void AddPage(CogSlabPage page)
    {
        _cogSlabPages.Add(page);
        UpdateSection();
    }

    /// <summary>
    /// Turns to the next/previous page, and updates the ui.
    /// </summary>
    /// <param name="number"></param> How many pages to turn, and in which direction (if negative)
    public void TurnPage(int number)
    {
        _currentPage = Math.Clamp(_currentPage + number, 0, _cogSlabPages.Count - 1);
        UpdateSection();
    }

    private void UpdateSection()
    {
        // The page holder holds the current page displayed, so we clear them
        PageHolder.DisposeAllChildren();

        if (_cogSlabPages.Count == 0)
            return;

        var pageToDisplay = _cogSlabPages[_currentPage];
        PageHolder.AddChild(pageToDisplay);

        // In order to show how many pages are left to the user
        PageCounter.Text = $"{_currentPage + 1} / {_cogSlabPages.Count}";

        // Whether we can display the buttons
        var visibilityCheck = _cogSlabPages.Count > 1;

        PrevButton.Visible = visibilityCheck;
        NextButton.Visible = visibilityCheck;

        PrevButton.Disabled = CanPressPrevButton;
        NextButton.Disabled = CanPressNextButton;
    }
}
