// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI;

[GenerateTypedNameReferences]
public sealed partial class CogSlabGuideSection : CogSlabSection
{
    public CogSlabGuideSection()
    {
        RobustXamlLoader.Load(this);
    }
}
