// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.ClockworkCult.UI;

/// <summary>
/// A CogSlabPage tries to mimic how actual books look like, with 2 paper pages and a seperator in the middle.
/// CogSlabPages are used by <see cref="CogSlabSection"/>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CogSlabPage : BoxContainer
{
    public CogSlabPage()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetPageTitle(string? title)
    {
        PageTitle.Text = title;
    }

    public void SetPageContent(string text)
    {
        // TODO: Dynamically fit it to both page contents based on text size bruh
        FirstPageContent.Text = text;
    }
}
